imports_granularity = "Crate"
reorder_imports = true
combine_control_expr = false
empty_item_single_line = false
enum_discrim_align_threshold = 50
fn_params_layout = "Vertical"
force_multiline_blocks = true
imports_layout = "Vertical"
reorder_impl_items = true